# // docker-compose.yml
 
version: '3.8'
 
services:
  mysql:
    image: mysql:latest
    container_name: mysql-intercal
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: maindb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ddl:/docker-entrypoint.initdb.d
 
volumes:
  mysql_data: